#include "time.h"
#include <stdlib.h>
#include <stdio.h> 
#include <string.h> 
#include <math.h>
#include "xc.h"

//Header Files
#include "Final_Project_Color_Sensor.h"
#include "Final_Project_Color_Moving_Average.h"
#include "Final_Project_LCD.h"
#include "Final_Project_Button.h"
#include "Final_Project_Game.h"
#include "Final_Project_Delay.h"

int codeCompare[4]; //compared code 
int masterCode[4] = {0,2,1,0}; //Random generated code
int userCode[4]; //User input codes
int winCond = 0;
int didYouWin = 0;

void masterCodeGen(void){
    /*
     * Function Desc.: Generates a random number from 0-4 for each element of an array.
     *                 1 = red, 2 = blue, 3 = green, 4 = black
     * Arguments: N/A
     * Peripherals: N/A
    */
    
    int colors[8];
    for(int masterIndex = 0; masterIndex < 4; masterIndex++){             
        int randomIndex = rand() % 4 + 0;
        masterCode[masterIndex] = colors[randomIndex];
    }
}

void calculateCompare(void){
    /*
     * Function Desc.: Loops through the sequence of 4 inputs given by user and compares it to the random sequence of 4
     *                 colors generated by the code. If the input and output match up in color and position, a 1 is written to the global code compare array.
     *                 If the input and output don't match up in either color or position, a 2 is written to the global code compare array. Lastly, if the input and output 
     *                 match in color but not in position, then a 0 is written to the global array.
     *                  
     * Arguments: N/A
     * Peripherals: N/A
    */    
    //(2) = x - completely wrong
    //(0) = 0 - there is a color in the code, wrong spot
    //(1) = 1 - correct color in the right spot
    int codePos;
    didYouWin = 0;
    //Color matches current place
    for(codePos = 0; codePos < 4; codePos++){
        int x = 0;
        if(userCode[codePos] == masterCode[codePos]){       //Correct color and spot
            codeCompare[codePos] = 1;
            didYouWin++;
        }       
        if(userCode[codePos] != masterCode[codePos]){       //Incorrect color but could be in a different spot          
            for(int i = 0; i < 4; i++){
                if(userCode[codePos] == masterCode[i]){     
                    codeCompare[codePos] = 0;               //color in different spot
                    x = 1;
                }
                else if((userCode[codePos] != masterCode[i]) && (x == 0)){
                    codeCompare[codePos] = 2;               //color not in sequence
                }
            }
        }
    }
}

void printCompare(int row){
    /*
     * Function Desc.: Loops through the global compare array and outputs a character depending on the element value.
     *                 2 = 'X', 1 = '1', and 0 = '0'
     * Arguments: "row" specifies what row to set the LCD cursor to so that the first try can be outputted to the first line,
     *            and the second try to the second line. 
     * Peripherals: LCD screen
    */
    lcd_setCursor(row,0);
    for(int pos = 0; pos < 4; pos++){    
        if(codeCompare[pos] == 0){  //there is a color in the code, wrong spot
            lcd_printChar('0');
        }
        if(codeCompare[pos] == 1){  //correct color in the right spot
            lcd_printChar('1');
        }
        if(codeCompare[pos] == 2){  //completely wrong
            lcd_printChar('X');
        }
    }
}

void winCondition(void){
    /*
     * Function Desc.: Uses the global variable "didYouWin" to keep track of how many correct guesses there are.
     *                 If the variable reaches 4, it measns that all 4 colors are guessed right and are in the right place. 
     * Arguments: N/A
     * Peripherals: N/A
    */
    
    //If the master and user codes are the same the user wins the game
    if(didYouWin == 4){  
        clearLCD();
        while(1){
        lcd_setCursor(0,0);
        lcd_printStr("YOU");
        lcd_setCursor(1,0);
        lcd_printStr("WIN!!!");
        }
    }
}